export const ENGLISH_KB = {
  meta: {
    region: '上海',
    curriculum: '牛津英语 Shanghai Edition(上海版) + 部分全国新课标补充',
    note: '上海小学三年级起步学英语(部分学校一年级起),初中六年级即「预备班」。中考以初三末为准,高考以高三末为准。',
  },
  grades: [
    {
      grade: '小学三年级',
      stage: 'primary',
      overview: '听说为主,字母与自然拼读入门,建立基本语感。重点不在书写,而在听音能懂、敢开口。',
      items: [
        { point: '26字母大小写认读与书写', difficulty: '基础', focus: '笔顺规范、四线三格占位、易混字母(b/d、p/q)区分', teaching: '用砂纸字母触摸+书空;每天5分钟默写抽5个;配合字母歌熟悉顺序。' },
        { point: '自然拼读入门(短元音 a/e/i/o/u)', difficulty: '重点', focus: 'CVC结构词的拼读(cat/dog/sit),区分短元音发音', teaching: '用字母卡玩拼读游戏;听音挑词;配合 Oxford Phonics 世界级卡片。' },
        { point: '问候与自我介绍', difficulty: '基础', focus: 'Hello/Hi/Good morning/My name is... 的得体使用', teaching: '角色扮演+头戴名牌;录视频回放让学生看到自己;鼓励加动作。' },
        { point: '颜色、数字1-20、家庭成员', difficulty: '基础', focus: '词汇量积累,数字13-15与30-50易混', teaching: '数实物(铅笔/糖果);家庭照片贴标签;What color? 接力问答。' },
        { point: 'I am / This is / It is 基本句型', difficulty: '重点', focus: '主谓一致与 be 动词变形,This is 不能说成 He is', teaching: '手偶对话;纠正不要打断,先复述正确版再说;句型卡片排序游戏。' },
        { point: '课堂指令语(Stand up/Sit down/Open your book)', difficulty: '基础', focus: '听懂并执行,不做中文翻译', teaching: 'TPR 全身反应法,老师下指令自己先做;Simon Says 游戏。' },
      ],
    },
    {
      grade: '小学四年级',
      stage: 'primary',
      overview: '开始系统学语法雏形:一般现在时第三人称单数是本年级最大难点。阅读从句子过渡到短段。',
      items: [
        { point: '一般现在时(第三人称单数 -s/-es)', difficulty: '难点', focus: 'he/she/it 后动词加 s,does/doesn\'t 否定疑问;学生极易遗忘', teaching: '设计「他的一天」描述任务;用红笔标注 s;对比 I play 与 He plays 配对练习。' },
        { point: '可数与不可数名词', difficulty: '重点', focus: 'a/an/some 的使用,water/bread/paper 不可数', teaching: '实物分类游戏;画「可数/不可数」两栏贴单词卡;much/many 提前渗透。' },
        { point: 'wh-疑问词(what/where/who/whose/how)', difficulty: '重点', focus: '根据答语选疑问词,whose 与 who 易混', teaching: '问答接龙;猜猜我是谁游戏;做「采访同学」任务。' },
        { point: '时间表达与频率副词', difficulty: '基础', focus: 'It\'s seven. / at seven / always/usually/often', teaching: '做纸盘钟面;记录自己一天的时间表;频率副词用条形图直观感受。' },
        { point: '食物、动物、科目词汇', difficulty: '基础', focus: '词汇量约 200+,开始有拼写压力', teaching: '分类记忆法;每周一词本;用思维导图按主题整理。' },
        { point: 'There is/are 句型', difficulty: '重点', focus: '单复数 be 动词选择,否定与疑问改换', teaching: '描述教室/卧室图;藏猫猫游戏(In the box, there is...);先单后复。' },
      ],
    },
    {
      grade: '小学五年级',
      stage: 'primary',
      overview: '现在进行时与一般过去时入门,写作从句子扩到 5 句小段。本年级是小学到初中的关键衔接点。',
      items: [
        { point: '现在进行时(be + V-ing)', difficulty: '重点', focus: 'be 动词与主语一致,ing 变形规则(running/swimming/taking)', teaching: '动作卡游戏;猜动作;看图说话;对比 He reads(习惯)与 He is reading(此刻)。' },
        { point: '一般过去时(规则 + be 动词 was/were)', difficulty: '难点', focus: '-ed 发音与不规则动词初识,was/were 与 was not/weren\'t', teaching: '昨天日记;故事复述;时间轴梳理;先学 was/were 再学规则 -ed。' },
        { point: '比较级入门(-er / more)', difficulty: '重点', focus: 'taller/bigger/more beautiful,than 句型', teaching: '同学两两比身高;物品比较;good/better、bad/worse 提前铺垫。' },
        { point: '情态动词 can/can\'t/must', difficulty: '重点', focus: '能力与规则的区分,can 后接动词原形', teaching: '我能你也能游戏;班级规则海报;Make rules 任务。' },
        { point: '段落写作(介绍人/地/物 5 句)', difficulty: '难点', focus: '主题句+支撑句+结尾句的结构意识', teaching: '填空式模板起步;好段落共赏;学生互评用三星(结构/拼写/内容)。' },
        { point: '阅读理解(细节+主旨)', difficulty: '重点', focus: '从「找答案」到「概括」过渡,开始有推断题', teaching: '5W 提问法;画思维导图;限时训练 3 分钟一篇。' },
      ],
    },
    {
      grade: '初中六年级(预备班)',
      stage: 'middle',
      overview: '上海初中起点年级,学生水平差异大。重点查漏补缺小学语法,同时引入初中阅读量与长篇。人称代词与物主是衔接核心。',
      items: [
        { point: '人称代词主宾格与物主代词', difficulty: '重点', focus: 'I/me/my/mine 全表,her 既宾格又物主易混', teaching: '替换练习(I→he 句型转换);物主代词用「这是谁的」游戏;表格化记忆。' },
        { point: '一般现在时综合复习(含频度副词)', difficulty: '基础', focus: '动词 s 规则、do/does 否定疑问、频度副词位置', teaching: '错题本;诊断式测试定薄弱点;造句接龙;不要从头教而是定点补。' },
        { point: '现在进行时 vs 一般现在时', difficulty: '难点', focus: '此刻动作 vs 习惯性动作的语境判断', teaching: '对比图组(he runs every day / he is running now);时间副词提示词训练。' },
        { point: '可数不可数 + how much/how many', difficulty: '重点', focus: 'some/any,a few/a little 区分', teaching: '超市购物清单;分类卡;a few/a little 用容器比喻(可数=豆子,不可数=水)。' },
        { point: '阅读:寻读与略读策略', difficulty: '重点', focus: '不再逐字翻译,学会抓关键词与段落首句', teaching: '限时 2 分钟读 300 字;圈关键词;段落首句加粗;做阅读笔记卡。' },
        { point: '写作:看图写话 6-8 句', difficulty: '难点', focus: '时态统一、连贯词 and/then/but 使用', teaching: '图组排序;先口头后笔头;教师批改只标 3 处重点不改全文。' },
        { point: '音标入门(20元音)', difficulty: '难点', focus: '长短板音区分、单元音与双元音、易混 /i/ 与 /i:/', teaching: '看口型视频;最小对立词听辨(sheep/ship);音标卡每日 5 个。' },
      ],
    },
    {
      grade: '初中七年级(初一)',
      stage: 'middle',
      overview: '一般过去时全面展开,开始接触复合句。词汇量要求陡增,阅读篇幅加长。中考阅读语感从此年奠定。',
      items: [
        { point: '一般过去时(不规则动词)', difficulty: '难点', focus: '约 80 个常见不规则动词 go-went-gone、buy-bought 等三态', teaching: '分组分类记忆(ABC/ABB/AAB型);过去时日记;故事接龙;不规则动词每日 5 个默写。' },
        { point: '过去进行时(was/were + V-ing)', difficulty: '重点', focus: '过去某时刻正在做、与一般过去时的对比(when/while)', teaching: '昨晚 8 点你在做什么;图组对比;While I was reading, he called 句型卡。' },
        { point: '一般将来时(will / be going to)', difficulty: '重点', focus: 'will 表预测/决定,be going to 表计划;瞬时决定用 will', teaching: '天气预报任务;周末计划卡;I think it will... 句型。' },
        { point: '形容词副词比较级与最高级', difficulty: '难点', focus: '不规则 good/better/best、as...as 句型、the + 最高级 + of/in', teaching: '三人比较;班级之最;as...as 用天平比喻;much/a little 修饰比较级。' },
        { point: '并列连词与复合句入门', difficulty: '重点', focus: 'and/but/or/so 与 because/when/if 区分使用', teaching: '句子合并练习;because 不与 so 连用纠错;if 引导条件句铺垫。' },
        { point: '阅读:细节+推断+词义猜测', difficulty: '重点', focus: '推断题(probably / the writer feels)是本年级新题型', teaching: '上下文猜词训练;标记推断信号词;做精读一篇+泛读三篇搭配。' },
        { point: '写作:记叙文一段(80词)', difficulty: '难点', focus: '六要素(who/when/where/what/why/how)、时态统一过去时', teaching: '故事山模板(开端-发展-高潮-结尾);好句积累本;只改一段不改全文。' },
      ],
    },
    {
      grade: '初中八年级(初二)',
      stage: 'middle',
      overview: '被动语态、现在完成时、定语从句三大重难点齐聚,是初中英语的分水岭。阅读篇幅 300-500 字,写作开始有议论文雏形。',
      items: [
        { point: '现在完成时(have/has + V-ed)', difficulty: '难点', focus: '与一般过去时的核心区别:影响现在 vs 过去动作;already/yet/ever/never/just 信号词', teaching: '人生经历清单(I have been to...);对比 He went(时间)与 He has gone(没回);时间轴画图。' },
        { point: '被动语态(一般现在/过去/将来)', difficulty: '难点', focus: 'be + done,主被动转换,by 短语;双宾语与含宾补的被动', teaching: '新闻标题改写;制作流程(纸是怎么做的);动作执行者不明时用被动。' },
        { point: '定语从句(关系代词 who/which/that)', difficulty: '难点', focus: '先行词为人用 who、物用 which,that 通用;限制性与非限制性初识', teaching: '猜词游戏(The boy who wears glasses is...);合并句子练习;定语从句不能套中文「的」语序。' },
        { point: '宾语从句(陈述/疑问/特殊疑问)', difficulty: '重点', focus: 'that/if/whether/wh- 引导,语序必须是陈述语序,时态呼应规则', teaching: '传话游戏;He said that... 句型转换;if vs whether 区分(有 or not 用 whether)。' },
        { point: '不定式与动名词(to do vs doing)', difficulty: '重点', focus: 'want/decide/hope + to do, enjoy/finish/mind + doing;stop to do vs stop doing', teaching: '动词分类表(接 to do / doing / 都可);stop to do vs stop doing 对比情境;记忆口诀。' },
        { point: '阅读:议论文结构与作者态度', difficulty: '重点', focus: '识别论点-论据-结论,作者态度题(author\'s attitude)', teaching: '三段论标记;态度形容词库(positive/negative/neutral);限时 5 分钟 400 字。' },
        { point: '写作:议论文一段(观点+理由+例证)', difficulty: '难点', focus: 'I think... because... For example... 结构模板', teaching: '正方反方辩论;话题库(手机该不该带学校);套模板起步后去模。' },
        { point: '词汇:词缀法构词', difficulty: '重点', focus: '-tion/-ment/-ness/-ful/-less/-un- 等常见词缀', teaching: '一词多词族(act→action→active→actively→activity);词树图画。' },
      ],
    },
    {
      grade: '初中九年级(初三·中考)',
      stage: 'middle',
      overview: '中考冲刺年。知识点复习为主,新内容仅虚拟语气等少量补充。重点在综合运用、答题技巧、写作成型。',
      items: [
        { point: '虚拟语气入门(wish/if only)', difficulty: '难点', focus: '与现在事实相反:were/would do;wish 表遗憾与祝愿', teaching: '三个愿望清单;If I were..., I would... 句型;与真实条件句对比。' },
        { point: '主谓一致综合(就近/语法一致/意义一致)', difficulty: '难点', focus: 'there be 就近、each/every + 单数、集体名词视语境', teaching: '主谓一致错题集;三原则对比表;不可数名词量化(a piece of)。' },
        { point: '中考阅读:6 大题型全覆盖', difficulty: '重点', focus: '细节/主旨/推断/词义/结构/态度,45 分钟 4 篇', teaching: '分题型专项;圈信号词;先看题再读文;不纠缠生词。' },
        { point: '中考完形填空:上下文逻辑', difficulty: '重点', focus: '词汇辨析 + 连贯推理,16 题约 12 分钟', teaching: '先通读后填空;选项分组(词义/语法/逻辑);首句不设空原则。' },
        { point: '中考写作:话题作文 80-100 词', difficulty: '难点', focus: '三段式(引入-展开-结尾)、连接词、亮点句', teaching: '10 大话题模板(环保/校园/科技/成长);亮点句库;同伴互评打分。' },
        { point: '听力:对话与短文', difficulty: '重点', focus: '数字时间地点细节题、长对话主旨题', teaching: '预读选项;速记符号(↑↓⏰$);数字专项(电话/价格/时间);每周一套限时。' },
        { point: '语法综合复习:12 大时态语态串联', difficulty: '难点', focus: '时态语态混合作辨析,易混点排查', teaching: '时态时间轴总图;错题本三轮复习;做混合语法选择 30 题专项。' },
        { point: '中考高频词汇 1500 复习', difficulty: '基础', focus: '考纲词汇全覆盖,熟词生义(hold 会议、develop 照片)', teaching: '艾宾浩斯循环;一词一卡带例句;熟词生义专项本。' },
      ],
    },
  ],
}
